// -----------List of Countries----------------
export const COUNTRIES_LIST = [
  { code: 'US', country: 'United States Of America' },
  { code: 'AD', country: 'Andorra' },
  { code: 'AI', country: 'Anguilla' },
  { code: 'AR', country: 'Argentina' },
  { code: 'AU', country: 'Australia' },
  { code: 'AT', country: 'Austria' },
  { code: 'AZ', country: 'Azerbaijan' },
  { code: 'BS', country: 'Bahamas' },
  { code: 'BH', country: 'Bahrain' },
  { code: 'BB', country: 'Barbados' },
  { code: 'BE', country: 'Belgium' },
  { code: 'BM', country: 'Bermuda' },
  { code: 'BR', country: 'Brazil' },
  { code: 'BG', country: 'Bulgaria' },
  { code: 'CA', country: 'Canada' },
  { code: 'CL', country: 'Chile' },
  { code: 'CN', country: 'China' },
  { code: 'CO', country: 'Colombia' },
  { code: 'CR', country: 'Costa Rica' },
  { code: 'HR', country: 'Croatia' },
  { code: 'CY', country: 'Cyprus' },
  { code: 'CZ', country: 'Czech Republic' },
  { code: 'DK', country: 'Denmark' },
  { code: 'DO', country: 'Dominican Republic' },
  { code: 'EC', country: 'Ecuador' },
  { code: 'EE', country: 'Estonia' },
  { code: 'FO', country: 'Faroe Islands' },
  { code: 'FI', country: 'Finland' },
  { code: 'FR', country: 'France' },
  { code: 'GE', country: 'Georgia' },
  { code: 'DE', country: 'Germany' },
  { code: 'GH', country: 'Ghana' },
  { code: 'GI', country: 'Gibraltar' },
  { code: 'GB', country: 'Great Britain' },
  { code: 'GR', country: 'Greece' },
  { code: 'HK', country: 'Hong Kong' },
  { code: 'HU', country: 'Hungary' },
  { code: 'IS', country: 'Iceland' },
  { code: 'IN', country: 'India' },
  { code: 'IE', country: 'Ireland' },
  { code: 'IL', country: 'Israel' },
  { code: 'IT', country: 'Italy' },
  { code: 'JM', country: 'Jamaica' },
  { code: 'JP', country: 'Japan' },
  { code: 'KR', country: 'Korea, Republic of' },
  { code: 'LV', country: 'Latvia' },
  { code: 'LB', country: 'Lebanon' },
  { code: 'LT', country: 'Lithuania' },
  { code: 'LU', country: 'Luxembourg' },
  { code: 'MY', country: 'Malaysia' },
  { code: 'MT', country: 'Malta' },
  { code: 'MX', country: 'Mexico' },
  { code: 'MC', country: 'Monaco' },
  { code: 'ME', country: 'Montenegro' },
  { code: 'MA', country: 'Morocco' },
  { code: 'NL', country: 'Netherlands' },
  { code: 'AN', country: 'Netherlands Antilles' },
  { code: 'NZ', country: 'New Zealand' },
  { code: 'ND', country: 'Northern Ireland' },
  { code: 'NO', country: 'Norway' },
  { code: 'PE', country: 'Peru' },
  { code: 'PL', country: 'Poland' },
  { code: 'PT', country: 'Portugal' },
  { code: 'RO', country: 'Romania' },
  { code: 'RU', country: 'Russian Federation' },
  { code: 'LC', country: 'Saint Lucia' },
  { code: 'SA', country: 'Saudi Arabia' },
  { code: 'RS', country: 'Serbia' },
  { code: 'SG', country: 'Singapore' },
  { code: 'SK', country: 'Slovakia' },
  { code: 'SI', country: 'Slovenia' },
  { code: 'ZA', country: 'South Africa' },
  { code: 'ES', country: 'Spain' },
  { code: 'SE', country: 'Sweden' },
  { code: 'CH', country: 'Switzerland' },
  { code: 'TW', country: 'Taiwan' },
  { code: 'TH', country: 'Thailand' },
  { code: 'TT', country: 'Trinidad and Tobago' },
  { code: 'TR', country: 'Turkey' },
  { code: 'UA', country: 'Ukraine' },
  { code: 'AE', country: 'United Arab Emirates' },
  { code: 'UY', country: 'Uruguay' },
  { code: 'VE', country: 'Venezuela' },
];
